FROM quay.io/aptible/alpine

ENV REDIS_VERSION <%= ENV.fetch 'REDIS_VERSION' %>
ENV REDIS_SHA1SUM <%= ENV.fetch 'REDIS_SHA1SUM' %>

ADD ./bin/install-redis.sh /install-redis.sh
RUN /install-redis.sh

# rdbtools is used for importing an RDB dump remotely.
RUN apk-install py-pip coreutils && pip install rdbtools
ADD templates/redis.conf /etc/redis.conf

ADD ./bin/run-database.sh /usr/bin/
ADD ./bin/utilities.sh /usr/bin/

ENV DATA_DIRECTORY /var/db
VOLUME ["$DATA_DIRECTORY"]

ENV CONFIG_DIRECTORY /etc/redis
VOLUME ["$CONFIG_DIRECTORY"]

# Integration tests
ADD test /tmp/test
RUN bats /tmp/test

EXPOSE 6379

ENTRYPOINT ["run-database.sh"]
